### ISSUE TITLE
Fail to build on NFD ndn-cxx 0.7.0

### ISSUE THREAD

**Issue by italovalcy** [evaCastro/ndn-signed-data#1]
Dear,

When trying to use the code on an update ndnSIM or Minindn environment, for example, with NFD / nan-cxx 0.7.0, the compilation process fails with many errors:

```
$ ./waf configure
Setting top to                           : /tmp/ndn-signed-data
Setting out to                           : /tmp/ndn-signed-data/build
Checking for 'g++' (C++ compiler)        : /usr/bin/g++
Checking supported CXXFLAGS              : -std=c++11
Checking supported CXXFLAGS              : -pedantic -Wall -O2 -g
Checking for program 'pkg-config'        : /usr/bin/pkg-config
Checking for 'libndn-cxx'                : yes
Checking boost includes                  : 1.65.1
Checking boost libs                      : ok
Checking for boost linkage               : ok
'configure' finished successfully (3.399s)
$ ./waf
Waf: Entering directory `/tmp/ndn-signed-data/build'
[1/8] Compiling src/consumer-signed-data1/consumer-signed-data1.cpp
[2/8] Compiling src/producer-signed-data1/producer-signed-data1.cpp
In file included from /usr/local/include/ndn-cxx/detail/tag-host.hpp:25:0,
                 from /usr/local/include/ndn-cxx/detail/packet-base.hpp:25,
                 from /usr/local/include/ndn-cxx/data.hpp:25,
                 from /usr/local/include/ndn-cxx/face.hpp:25,
                 from ../src/producer-signed-data1/producer-signed-data1.cpp:3:
/usr/local/include/ndn-cxx/detail/common.hpp:35:2: error: #error "ndn-cxx applications must be compiled using the C++14 standard (-std=c++14)"
 #error "ndn-cxx applications must be compiled using the C++14 standard (-std=c++14)"
  ^~~~~
In file included from /usr/local/include/ndn-cxx/detail/tag-host.hpp:25:0,
                 from /usr/local/include/ndn-cxx/detail/packet-base.hpp:25,
                 from /usr/local/include/ndn-cxx/data.hpp:25,
                 from /usr/local/include/ndn-cxx/face.hpp:25,
                 from ../src/producer-signed-data1/producer-signed-data1.cpp:3:
/usr/local/include/ndn-cxx/detail/common.hpp:70:12: error: ‘std::make_unique’ has not been declared
 using std::make_unique;
            ^~~~~~~~~~~
/usr/local/include/ndn-cxx/detail/common.hpp:81:22: error: ‘string_literals’ is not a namespace-name
 using namespace std::string_literals;
...
../src/producer-signed-data1/producer-signed-data1.cpp:55:10: note: suggested alternative: ‘count’
     std::cout << "Signature. KeyLocator: " <<
          ^~~~
          count
../src/producer-signed-data1/producer-signed-data1.cpp:56:36: warning: ‘ndn::Signature ndn::Data::getSignature() const’ is deprecated: use getSignatureInfo and getSignatureValue [-Wdeprecated-declarations]
                 data->getSignature().getKeyLocator().getName() << std::endl;
                                    ^
In file included from /usr/local/include/ndn-cxx/face.hpp:25:0,
                 from ../src/producer-signed-data1/producer-signed-data1.cpp:3:
/usr/local/include/ndn-cxx/data.hpp:186:3: note: declared here
   getSignature() const;
   ^~~~~~~~~~~~
...
```

Some of the calls for signing and key management were updated on ndn-cxx. Updating the repo make it easy to test the scenario on newer versions.
